### PR TITLE
feat(workflow): Create overview as a part of import and standardised workflow

### PR DESCRIPTION
**Pull request by Wentao-Kuang**

### CODE REVIEW

**Comment by Wentao-Kuang** [comment]
@blacha @paulfouquet How do we release the changes for standardised workflow into argo?

**Comment by paulfouquet** [comment]
> @blacha @paulfouquet How do we release the changes for standardised workflow into argo?

Once your PR is merged: https://github.com/linz/topo-workflows/blob/master/.github/workflows/main.yml

**Comment by Wentao-Kuang** [comment]
> > @blacha @paulfouquet How do we release the changes for standardised workflow into argo?
> 
> Once your PR is merged: https://github.com/linz/topo-workflows/blob/master/.github/workflows/main.yml

Awesome, does this include the basemaps workflows?

**Comment by paulfouquet** [comment]
> Awesome, does this include the basemaps workflows?

Any `WorkflowTemplate`
```
# Find all workflows that have kind "WorkflowTemplate"
          WORKFLOWS=$(grep '^kind: WorkflowTemplate$' -R workflows/ -H | cut -d ':' -f1)
          # For each workflow attempt to deploy it using kubectl
          for wf in $WORKFLOWS; do
              kubectl apply -f $wf --namespace argo
          done
```

**Comment by Wentao-Kuang** [comment]
> > Awesome, does this include the basemaps workflows?
> 
> Any `WorkflowTemplate`
> 
> ```
> # Find all workflows that have kind "WorkflowTemplate"
>           WORKFLOWS=$(grep '^kind: WorkflowTemplate$' -R workflows/ -H | cut -d ':' -f1)
>           # For each workflow attempt to deploy it using kubectl
>           for wf in $WORKFLOWS; do
>               kubectl apply -f $wf --namespace argo
>           done
> ```

How do you make the version number changes comes after the workflow t

**Review by paulfouquet — APPROVED** [review]

**Comment by paulfouquet** [comment]
> > > Awesome, does this include the basemaps workflows?
> > 
> > 
> > Any `WorkflowTemplate`
> > ```
> > # Find all workflows that have kind "WorkflowTemplate"
> >           WORKFLOWS=$(grep '^kind: WorkflowTemplate$' -R workflows/ -H | cut -d ':' -f1)
> >           # For each workflow attempt to deploy it using kubectl
> >           for wf in $WORKFLOWS; do
> >               kubectl apply -f $wf --namespace argo
> >           done
> > ```
> 
> How do you make the version number changes comes after the workflow t

You'll need to manage that manually in your changes. If your a previous WorkflowTemplate with the same name (i.e. same version) already exists in Argo it will be overwritten.

**Review by blacha — APPROVED** [review]

**Pull request merged**
